// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BluetoothChannelData.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_BluetoothChannelData_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_BluetoothChannelData_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "BluetoothPairingMethodEnum.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_BluetoothChannelData_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_BluetoothChannelData_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_BluetoothChannelData_2eproto;
namespace f1x {
namespace aasdk {
namespace proto {
namespace data {
class BluetoothChannel;
class BluetoothChannelDefaultTypeInternal;
extern BluetoothChannelDefaultTypeInternal _BluetoothChannel_default_instance_;
}  // namespace data
}  // namespace proto
}  // namespace aasdk
}  // namespace f1x
PROTOBUF_NAMESPACE_OPEN
template<> ::f1x::aasdk::proto::data::BluetoothChannel* Arena::CreateMaybeMessage<::f1x::aasdk::proto::data::BluetoothChannel>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace f1x {
namespace aasdk {
namespace proto {
namespace data {

// ===================================================================

class BluetoothChannel PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:f1x.aasdk.proto.data.BluetoothChannel) */ {
 public:
  inline BluetoothChannel() : BluetoothChannel(nullptr) {};
  virtual ~BluetoothChannel();

  BluetoothChannel(const BluetoothChannel& from);
  BluetoothChannel(BluetoothChannel&& from) noexcept
    : BluetoothChannel() {
    *this = ::std::move(from);
  }

  inline BluetoothChannel& operator=(const BluetoothChannel& from) {
    CopyFrom(from);
    return *this;
  }
  inline BluetoothChannel& operator=(BluetoothChannel&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const BluetoothChannel& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const BluetoothChannel* internal_default_instance() {
    return reinterpret_cast<const BluetoothChannel*>(
               &_BluetoothChannel_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(BluetoothChannel& a, BluetoothChannel& b) {
    a.Swap(&b);
  }
  inline void Swap(BluetoothChannel* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BluetoothChannel* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline BluetoothChannel* New() const final {
    return CreateMaybeMessage<BluetoothChannel>(nullptr);
  }

  BluetoothChannel* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<BluetoothChannel>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const BluetoothChannel& from);
  void MergeFrom(const BluetoothChannel& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BluetoothChannel* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "f1x.aasdk.proto.data.BluetoothChannel";
  }
  protected:
  explicit BluetoothChannel(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_BluetoothChannelData_2eproto);
    return ::descriptor_table_BluetoothChannelData_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSupportedPairingMethodsFieldNumber = 2,
    kAdapterAddressFieldNumber = 1,
  };
  // repeated .f1x.aasdk.proto.enums.BluetoothPairingMethod.Enum supported_pairing_methods = 2;
  int supported_pairing_methods_size() const;
  private:
  int _internal_supported_pairing_methods_size() const;
  public:
  void clear_supported_pairing_methods();
  private:
  ::f1x::aasdk::proto::enums::BluetoothPairingMethod_Enum _internal_supported_pairing_methods(int index) const;
  void _internal_add_supported_pairing_methods(::f1x::aasdk::proto::enums::BluetoothPairingMethod_Enum value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>* _internal_mutable_supported_pairing_methods();
  public:
  ::f1x::aasdk::proto::enums::BluetoothPairingMethod_Enum supported_pairing_methods(int index) const;
  void set_supported_pairing_methods(int index, ::f1x::aasdk::proto::enums::BluetoothPairingMethod_Enum value);
  void add_supported_pairing_methods(::f1x::aasdk::proto::enums::BluetoothPairingMethod_Enum value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>& supported_pairing_methods() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>* mutable_supported_pairing_methods();

  // string adapter_address = 1;
  void clear_adapter_address();
  const std::string& adapter_address() const;
  void set_adapter_address(const std::string& value);
  void set_adapter_address(std::string&& value);
  void set_adapter_address(const char* value);
  void set_adapter_address(const char* value, size_t size);
  std::string* mutable_adapter_address();
  std::string* release_adapter_address();
  void set_allocated_adapter_address(std::string* adapter_address);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_adapter_address();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_adapter_address(
      std::string* adapter_address);
  private:
  const std::string& _internal_adapter_address() const;
  void _internal_set_adapter_address(const std::string& value);
  std::string* _internal_mutable_adapter_address();
  public:

  // @@protoc_insertion_point(class_scope:f1x.aasdk.proto.data.BluetoothChannel)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField<int> supported_pairing_methods_;
  mutable std::atomic<int> _supported_pairing_methods_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr adapter_address_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_BluetoothChannelData_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// BluetoothChannel

// string adapter_address = 1;
inline void BluetoothChannel::clear_adapter_address() {
  adapter_address_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& BluetoothChannel::adapter_address() const {
  // @@protoc_insertion_point(field_get:f1x.aasdk.proto.data.BluetoothChannel.adapter_address)
  return _internal_adapter_address();
}
inline void BluetoothChannel::set_adapter_address(const std::string& value) {
  _internal_set_adapter_address(value);
  // @@protoc_insertion_point(field_set:f1x.aasdk.proto.data.BluetoothChannel.adapter_address)
}
inline std::string* BluetoothChannel::mutable_adapter_address() {
  // @@protoc_insertion_point(field_mutable:f1x.aasdk.proto.data.BluetoothChannel.adapter_address)
  return _internal_mutable_adapter_address();
}
inline const std::string& BluetoothChannel::_internal_adapter_address() const {
  return adapter_address_.Get();
}
inline void BluetoothChannel::_internal_set_adapter_address(const std::string& value) {
  
  adapter_address_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void BluetoothChannel::set_adapter_address(std::string&& value) {
  
  adapter_address_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:f1x.aasdk.proto.data.BluetoothChannel.adapter_address)
}
inline void BluetoothChannel::set_adapter_address(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  adapter_address_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:f1x.aasdk.proto.data.BluetoothChannel.adapter_address)
}
inline void BluetoothChannel::set_adapter_address(const char* value,
    size_t size) {
  
  adapter_address_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:f1x.aasdk.proto.data.BluetoothChannel.adapter_address)
}
inline std::string* BluetoothChannel::_internal_mutable_adapter_address() {
  
  return adapter_address_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* BluetoothChannel::release_adapter_address() {
  // @@protoc_insertion_point(field_release:f1x.aasdk.proto.data.BluetoothChannel.adapter_address)
  return adapter_address_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void BluetoothChannel::set_allocated_adapter_address(std::string* adapter_address) {
  if (adapter_address != nullptr) {
    
  } else {
    
  }
  adapter_address_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), adapter_address,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:f1x.aasdk.proto.data.BluetoothChannel.adapter_address)
}
inline std::string* BluetoothChannel::unsafe_arena_release_adapter_address() {
  // @@protoc_insertion_point(field_unsafe_arena_release:f1x.aasdk.proto.data.BluetoothChannel.adapter_address)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return adapter_address_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void BluetoothChannel::unsafe_arena_set_allocated_adapter_address(
    std::string* adapter_address) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (adapter_address != nullptr) {
    
  } else {
    
  }
  adapter_address_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      adapter_address, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:f1x.aasdk.proto.data.BluetoothChannel.adapter_address)
}

// repeated .f1x.aasdk.proto.enums.BluetoothPairingMethod.Enum supported_pairing_methods = 2;
inline int BluetoothChannel::_internal_supported_pairing_methods_size() const {
  return supported_pairing_methods_.size();
}
inline int BluetoothChannel::supported_pairing_methods_size() const {
  return _internal_supported_pairing_methods_size();
}
inline void BluetoothChannel::clear_supported_pairing_methods() {
  supported_pairing_methods_.Clear();
}
inline ::f1x::aasdk::proto::enums::BluetoothPairingMethod_Enum BluetoothChannel::_internal_supported_pairing_methods(int index) const {
  return static_cast< ::f1x::aasdk::proto::enums::BluetoothPairingMethod_Enum >(supported_pairing_methods_.Get(index));
}
inline ::f1x::aasdk::proto::enums::BluetoothPairingMethod_Enum BluetoothChannel::supported_pairing_methods(int index) const {
  // @@protoc_insertion_point(field_get:f1x.aasdk.proto.data.BluetoothChannel.supported_pairing_methods)
  return _internal_supported_pairing_methods(index);
}
inline void BluetoothChannel::set_supported_pairing_methods(int index, ::f1x::aasdk::proto::enums::BluetoothPairingMethod_Enum value) {
  supported_pairing_methods_.Set(index, value);
  // @@protoc_insertion_point(field_set:f1x.aasdk.proto.data.BluetoothChannel.supported_pairing_methods)
}
inline void BluetoothChannel::_internal_add_supported_pairing_methods(::f1x::aasdk::proto::enums::BluetoothPairingMethod_Enum value) {
  supported_pairing_methods_.Add(value);
}
inline void BluetoothChannel::add_supported_pairing_methods(::f1x::aasdk::proto::enums::BluetoothPairingMethod_Enum value) {
  // @@protoc_insertion_point(field_add:f1x.aasdk.proto.data.BluetoothChannel.supported_pairing_methods)
  _internal_add_supported_pairing_methods(value);
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>&
BluetoothChannel::supported_pairing_methods() const {
  // @@protoc_insertion_point(field_list:f1x.aasdk.proto.data.BluetoothChannel.supported_pairing_methods)
  return supported_pairing_methods_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>*
BluetoothChannel::_internal_mutable_supported_pairing_methods() {
  return &supported_pairing_methods_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>*
BluetoothChannel::mutable_supported_pairing_methods() {
  // @@protoc_insertion_point(field_mutable_list:f1x.aasdk.proto.data.BluetoothChannel.supported_pairing_methods)
  return _internal_mutable_supported_pairing_methods();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace data
}  // namespace proto
}  // namespace aasdk
}  // namespace f1x

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_BluetoothChannelData_2eproto
