// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ButtonEventData.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ButtonEventData_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ButtonEventData_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ButtonEventData_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ButtonEventData_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ButtonEventData_2eproto;
namespace f1x {
namespace aasdk {
namespace proto {
namespace data {
class ButtonEvent;
class ButtonEventDefaultTypeInternal;
extern ButtonEventDefaultTypeInternal _ButtonEvent_default_instance_;
}  // namespace data
}  // namespace proto
}  // namespace aasdk
}  // namespace f1x
PROTOBUF_NAMESPACE_OPEN
template<> ::f1x::aasdk::proto::data::ButtonEvent* Arena::CreateMaybeMessage<::f1x::aasdk::proto::data::ButtonEvent>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace f1x {
namespace aasdk {
namespace proto {
namespace data {

// ===================================================================

class ButtonEvent PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:f1x.aasdk.proto.data.ButtonEvent) */ {
 public:
  inline ButtonEvent() : ButtonEvent(nullptr) {};
  virtual ~ButtonEvent();

  ButtonEvent(const ButtonEvent& from);
  ButtonEvent(ButtonEvent&& from) noexcept
    : ButtonEvent() {
    *this = ::std::move(from);
  }

  inline ButtonEvent& operator=(const ButtonEvent& from) {
    CopyFrom(from);
    return *this;
  }
  inline ButtonEvent& operator=(ButtonEvent&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ButtonEvent& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ButtonEvent* internal_default_instance() {
    return reinterpret_cast<const ButtonEvent*>(
               &_ButtonEvent_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ButtonEvent& a, ButtonEvent& b) {
    a.Swap(&b);
  }
  inline void Swap(ButtonEvent* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ButtonEvent* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ButtonEvent* New() const final {
    return CreateMaybeMessage<ButtonEvent>(nullptr);
  }

  ButtonEvent* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ButtonEvent>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ButtonEvent& from);
  void MergeFrom(const ButtonEvent& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ButtonEvent* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "f1x.aasdk.proto.data.ButtonEvent";
  }
  protected:
  explicit ButtonEvent(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ButtonEventData_2eproto);
    return ::descriptor_table_ButtonEventData_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kScanCodeFieldNumber = 1,
    kMetaFieldNumber = 3,
    kIsPressedFieldNumber = 2,
    kLongPressFieldNumber = 4,
  };
  // uint32 scan_code = 1;
  void clear_scan_code();
  ::PROTOBUF_NAMESPACE_ID::uint32 scan_code() const;
  void set_scan_code(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_scan_code() const;
  void _internal_set_scan_code(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 meta = 3;
  void clear_meta();
  ::PROTOBUF_NAMESPACE_ID::uint32 meta() const;
  void set_meta(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_meta() const;
  void _internal_set_meta(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // bool is_pressed = 2;
  void clear_is_pressed();
  bool is_pressed() const;
  void set_is_pressed(bool value);
  private:
  bool _internal_is_pressed() const;
  void _internal_set_is_pressed(bool value);
  public:

  // bool long_press = 4;
  void clear_long_press();
  bool long_press() const;
  void set_long_press(bool value);
  private:
  bool _internal_long_press() const;
  void _internal_set_long_press(bool value);
  public:

  // @@protoc_insertion_point(class_scope:f1x.aasdk.proto.data.ButtonEvent)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::uint32 scan_code_;
  ::PROTOBUF_NAMESPACE_ID::uint32 meta_;
  bool is_pressed_;
  bool long_press_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ButtonEventData_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ButtonEvent

// uint32 scan_code = 1;
inline void ButtonEvent::clear_scan_code() {
  scan_code_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ButtonEvent::_internal_scan_code() const {
  return scan_code_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ButtonEvent::scan_code() const {
  // @@protoc_insertion_point(field_get:f1x.aasdk.proto.data.ButtonEvent.scan_code)
  return _internal_scan_code();
}
inline void ButtonEvent::_internal_set_scan_code(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  scan_code_ = value;
}
inline void ButtonEvent::set_scan_code(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_scan_code(value);
  // @@protoc_insertion_point(field_set:f1x.aasdk.proto.data.ButtonEvent.scan_code)
}

// bool is_pressed = 2;
inline void ButtonEvent::clear_is_pressed() {
  is_pressed_ = false;
}
inline bool ButtonEvent::_internal_is_pressed() const {
  return is_pressed_;
}
inline bool ButtonEvent::is_pressed() const {
  // @@protoc_insertion_point(field_get:f1x.aasdk.proto.data.ButtonEvent.is_pressed)
  return _internal_is_pressed();
}
inline void ButtonEvent::_internal_set_is_pressed(bool value) {
  
  is_pressed_ = value;
}
inline void ButtonEvent::set_is_pressed(bool value) {
  _internal_set_is_pressed(value);
  // @@protoc_insertion_point(field_set:f1x.aasdk.proto.data.ButtonEvent.is_pressed)
}

// uint32 meta = 3;
inline void ButtonEvent::clear_meta() {
  meta_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ButtonEvent::_internal_meta() const {
  return meta_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ButtonEvent::meta() const {
  // @@protoc_insertion_point(field_get:f1x.aasdk.proto.data.ButtonEvent.meta)
  return _internal_meta();
}
inline void ButtonEvent::_internal_set_meta(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  meta_ = value;
}
inline void ButtonEvent::set_meta(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_meta(value);
  // @@protoc_insertion_point(field_set:f1x.aasdk.proto.data.ButtonEvent.meta)
}

// bool long_press = 4;
inline void ButtonEvent::clear_long_press() {
  long_press_ = false;
}
inline bool ButtonEvent::_internal_long_press() const {
  return long_press_;
}
inline bool ButtonEvent::long_press() const {
  // @@protoc_insertion_point(field_get:f1x.aasdk.proto.data.ButtonEvent.long_press)
  return _internal_long_press();
}
inline void ButtonEvent::_internal_set_long_press(bool value) {
  
  long_press_ = value;
}
inline void ButtonEvent::set_long_press(bool value) {
  _internal_set_long_press(value);
  // @@protoc_insertion_point(field_set:f1x.aasdk.proto.data.ButtonEvent.long_press)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace data
}  // namespace proto
}  // namespace aasdk
}  // namespace f1x

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ButtonEventData_2eproto
