// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DoorData.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_DoorData_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_DoorData_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_DoorData_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_DoorData_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_DoorData_2eproto;
namespace f1x {
namespace aasdk {
namespace proto {
namespace data {
class Door;
class DoorDefaultTypeInternal;
extern DoorDefaultTypeInternal _Door_default_instance_;
}  // namespace data
}  // namespace proto
}  // namespace aasdk
}  // namespace f1x
PROTOBUF_NAMESPACE_OPEN
template<> ::f1x::aasdk::proto::data::Door* Arena::CreateMaybeMessage<::f1x::aasdk::proto::data::Door>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace f1x {
namespace aasdk {
namespace proto {
namespace data {

// ===================================================================

class Door PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:f1x.aasdk.proto.data.Door) */ {
 public:
  inline Door() : Door(nullptr) {};
  virtual ~Door();

  Door(const Door& from);
  Door(Door&& from) noexcept
    : Door() {
    *this = ::std::move(from);
  }

  inline Door& operator=(const Door& from) {
    CopyFrom(from);
    return *this;
  }
  inline Door& operator=(Door&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Door& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Door* internal_default_instance() {
    return reinterpret_cast<const Door*>(
               &_Door_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Door& a, Door& b) {
    a.Swap(&b);
  }
  inline void Swap(Door* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Door* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Door* New() const final {
    return CreateMaybeMessage<Door>(nullptr);
  }

  Door* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Door>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Door& from);
  void MergeFrom(const Door& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Door* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "f1x.aasdk.proto.data.Door";
  }
  protected:
  explicit Door(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_DoorData_2eproto);
    return ::descriptor_table_DoorData_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDoorOpenFieldNumber = 3,
    kHoodOpenFieldNumber = 1,
    kBootOpenFieldNumber = 2,
  };
  // repeated bool door_open = 3;
  int door_open_size() const;
  private:
  int _internal_door_open_size() const;
  public:
  void clear_door_open();
  private:
  bool _internal_door_open(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< bool >&
      _internal_door_open() const;
  void _internal_add_door_open(bool value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< bool >*
      _internal_mutable_door_open();
  public:
  bool door_open(int index) const;
  void set_door_open(int index, bool value);
  void add_door_open(bool value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< bool >&
      door_open() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< bool >*
      mutable_door_open();

  // bool hood_open = 1;
  void clear_hood_open();
  bool hood_open() const;
  void set_hood_open(bool value);
  private:
  bool _internal_hood_open() const;
  void _internal_set_hood_open(bool value);
  public:

  // bool boot_open = 2;
  void clear_boot_open();
  bool boot_open() const;
  void set_boot_open(bool value);
  private:
  bool _internal_boot_open() const;
  void _internal_set_boot_open(bool value);
  public:

  // @@protoc_insertion_point(class_scope:f1x.aasdk.proto.data.Door)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< bool > door_open_;
  mutable std::atomic<int> _door_open_cached_byte_size_;
  bool hood_open_;
  bool boot_open_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_DoorData_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Door

// bool hood_open = 1;
inline void Door::clear_hood_open() {
  hood_open_ = false;
}
inline bool Door::_internal_hood_open() const {
  return hood_open_;
}
inline bool Door::hood_open() const {
  // @@protoc_insertion_point(field_get:f1x.aasdk.proto.data.Door.hood_open)
  return _internal_hood_open();
}
inline void Door::_internal_set_hood_open(bool value) {
  
  hood_open_ = value;
}
inline void Door::set_hood_open(bool value) {
  _internal_set_hood_open(value);
  // @@protoc_insertion_point(field_set:f1x.aasdk.proto.data.Door.hood_open)
}

// bool boot_open = 2;
inline void Door::clear_boot_open() {
  boot_open_ = false;
}
inline bool Door::_internal_boot_open() const {
  return boot_open_;
}
inline bool Door::boot_open() const {
  // @@protoc_insertion_point(field_get:f1x.aasdk.proto.data.Door.boot_open)
  return _internal_boot_open();
}
inline void Door::_internal_set_boot_open(bool value) {
  
  boot_open_ = value;
}
inline void Door::set_boot_open(bool value) {
  _internal_set_boot_open(value);
  // @@protoc_insertion_point(field_set:f1x.aasdk.proto.data.Door.boot_open)
}

// repeated bool door_open = 3;
inline int Door::_internal_door_open_size() const {
  return door_open_.size();
}
inline int Door::door_open_size() const {
  return _internal_door_open_size();
}
inline void Door::clear_door_open() {
  door_open_.Clear();
}
inline bool Door::_internal_door_open(int index) const {
  return door_open_.Get(index);
}
inline bool Door::door_open(int index) const {
  // @@protoc_insertion_point(field_get:f1x.aasdk.proto.data.Door.door_open)
  return _internal_door_open(index);
}
inline void Door::set_door_open(int index, bool value) {
  door_open_.Set(index, value);
  // @@protoc_insertion_point(field_set:f1x.aasdk.proto.data.Door.door_open)
}
inline void Door::_internal_add_door_open(bool value) {
  door_open_.Add(value);
}
inline void Door::add_door_open(bool value) {
  _internal_add_door_open(value);
  // @@protoc_insertion_point(field_add:f1x.aasdk.proto.data.Door.door_open)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< bool >&
Door::_internal_door_open() const {
  return door_open_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< bool >&
Door::door_open() const {
  // @@protoc_insertion_point(field_list:f1x.aasdk.proto.data.Door.door_open)
  return _internal_door_open();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< bool >*
Door::_internal_mutable_door_open() {
  return &door_open_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< bool >*
Door::mutable_door_open() {
  // @@protoc_insertion_point(field_mutable_list:f1x.aasdk.proto.data.Door.door_open)
  return _internal_mutable_door_open();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace data
}  // namespace proto
}  // namespace aasdk
}  // namespace f1x

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_DoorData_2eproto
