// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SteeringWheelData.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_SteeringWheelData_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_SteeringWheelData_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_SteeringWheelData_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_SteeringWheelData_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_SteeringWheelData_2eproto;
namespace f1x {
namespace aasdk {
namespace proto {
namespace data {
class SteeringWheel;
class SteeringWheelDefaultTypeInternal;
extern SteeringWheelDefaultTypeInternal _SteeringWheel_default_instance_;
}  // namespace data
}  // namespace proto
}  // namespace aasdk
}  // namespace f1x
PROTOBUF_NAMESPACE_OPEN
template<> ::f1x::aasdk::proto::data::SteeringWheel* Arena::CreateMaybeMessage<::f1x::aasdk::proto::data::SteeringWheel>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace f1x {
namespace aasdk {
namespace proto {
namespace data {

// ===================================================================

class SteeringWheel PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:f1x.aasdk.proto.data.SteeringWheel) */ {
 public:
  inline SteeringWheel() : SteeringWheel(nullptr) {};
  virtual ~SteeringWheel();

  SteeringWheel(const SteeringWheel& from);
  SteeringWheel(SteeringWheel&& from) noexcept
    : SteeringWheel() {
    *this = ::std::move(from);
  }

  inline SteeringWheel& operator=(const SteeringWheel& from) {
    CopyFrom(from);
    return *this;
  }
  inline SteeringWheel& operator=(SteeringWheel&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const SteeringWheel& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SteeringWheel* internal_default_instance() {
    return reinterpret_cast<const SteeringWheel*>(
               &_SteeringWheel_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SteeringWheel& a, SteeringWheel& b) {
    a.Swap(&b);
  }
  inline void Swap(SteeringWheel* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SteeringWheel* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline SteeringWheel* New() const final {
    return CreateMaybeMessage<SteeringWheel>(nullptr);
  }

  SteeringWheel* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<SteeringWheel>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const SteeringWheel& from);
  void MergeFrom(const SteeringWheel& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SteeringWheel* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "f1x.aasdk.proto.data.SteeringWheel";
  }
  protected:
  explicit SteeringWheel(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_SteeringWheelData_2eproto);
    return ::descriptor_table_SteeringWheelData_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSteeringAngleFieldNumber = 1,
    kWheelSpeedFieldNumber = 2,
  };
  // int32 steering_angle = 1;
  void clear_steering_angle();
  ::PROTOBUF_NAMESPACE_ID::int32 steering_angle() const;
  void set_steering_angle(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_steering_angle() const;
  void _internal_set_steering_angle(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 wheel_speed = 2;
  void clear_wheel_speed();
  ::PROTOBUF_NAMESPACE_ID::int32 wheel_speed() const;
  void set_wheel_speed(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_wheel_speed() const;
  void _internal_set_wheel_speed(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:f1x.aasdk.proto.data.SteeringWheel)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::int32 steering_angle_;
  ::PROTOBUF_NAMESPACE_ID::int32 wheel_speed_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_SteeringWheelData_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SteeringWheel

// int32 steering_angle = 1;
inline void SteeringWheel::clear_steering_angle() {
  steering_angle_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 SteeringWheel::_internal_steering_angle() const {
  return steering_angle_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 SteeringWheel::steering_angle() const {
  // @@protoc_insertion_point(field_get:f1x.aasdk.proto.data.SteeringWheel.steering_angle)
  return _internal_steering_angle();
}
inline void SteeringWheel::_internal_set_steering_angle(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  steering_angle_ = value;
}
inline void SteeringWheel::set_steering_angle(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_steering_angle(value);
  // @@protoc_insertion_point(field_set:f1x.aasdk.proto.data.SteeringWheel.steering_angle)
}

// int32 wheel_speed = 2;
inline void SteeringWheel::clear_wheel_speed() {
  wheel_speed_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 SteeringWheel::_internal_wheel_speed() const {
  return wheel_speed_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 SteeringWheel::wheel_speed() const {
  // @@protoc_insertion_point(field_get:f1x.aasdk.proto.data.SteeringWheel.wheel_speed)
  return _internal_wheel_speed();
}
inline void SteeringWheel::_internal_set_wheel_speed(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  wheel_speed_ = value;
}
inline void SteeringWheel::set_wheel_speed(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_wheel_speed(value);
  // @@protoc_insertion_point(field_set:f1x.aasdk.proto.data.SteeringWheel.wheel_speed)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace data
}  // namespace proto
}  // namespace aasdk
}  // namespace f1x

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_SteeringWheelData_2eproto
